/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unir.plataformas;

import java.util.List;
import java.util.ArrayList;
import javax.swing.JFrame;
import net.unir.plataformas.modelo.Medicamento;
import net.unir.plataformas.modelo.Pedido;

/**
 *
 * @author casa
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }
    public JFrame pedido;
    
    /**
     * Método para Limpiar el Formulario
     */
    public void limpiarFormulario() {
        txtNombre.setText("");
        cbxTipo.setSelectedItem(null);
        cbxTipo.setSelectedItem(null);
        rbDistribuidor1.setSelected(false);
        rbDistribuidor2.setSelected(false);
        rbDistribuidor3.setSelected(false);
        chkSucursal1.setSelected(false);
        chkSucursal2.setSelected(false);
        spinCantidad.setValue(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpDistribuidor = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        spinCantidad = new javax.swing.JSpinner();
        rbDistribuidor1 = new javax.swing.JRadioButton();
        rbDistribuidor2 = new javax.swing.JRadioButton();
        rbDistribuidor3 = new javax.swing.JRadioButton();
        cbxTipo = new javax.swing.JComboBox<>();
        chkSucursal1 = new javax.swing.JCheckBox();
        chkSucursal2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Tipo:");

        jLabel3.setText("Cantidad:");

        jLabel4.setText("Distribuidor:");

        jLabel6.setText("Sucursal:");

        grpDistribuidor.add(rbDistribuidor1);
        rbDistribuidor1.setText("Cofarma");
        rbDistribuidor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDistribuidor1ActionPerformed(evt);
            }
        });

        grpDistribuidor.add(rbDistribuidor2);
        rbDistribuidor2.setText("Empsephar");
        rbDistribuidor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDistribuidor2ActionPerformed(evt);
            }
        });

        grpDistribuidor.add(rbDistribuidor3);
        rbDistribuidor3.setText("Cemefar");
        rbDistribuidor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDistribuidor3ActionPerformed(evt);
            }
        });

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo", "Antibiótico" }));

        chkSucursal1.setText("Principal");

        chkSucursal2.setText("Secundaria");

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtError.setBackground(new java.awt.Color(0, 0, 153));
        txtError.setForeground(new java.awt.Color(255, 255, 255));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbDistribuidor3)
                                    .addComponent(rbDistribuidor2)
                                    .addComponent(rbDistribuidor1)
                                    .addComponent(txtNombre)
                                    .addComponent(cbxTipo, 0, 186, Short.MAX_VALUE)
                                    .addComponent(spinCantidad)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkSucursal2)
                                    .addComponent(chkSucursal1))
                                .addGap(18, 18, 18)))
                        .addContainerGap(114, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDistribuidor1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDistribuidor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDistribuidor3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chkSucursal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSucursal2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(txtError, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbDistribuidor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDistribuidor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDistribuidor1ActionPerformed

    private void rbDistribuidor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDistribuidor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDistribuidor2ActionPerformed

    private void rbDistribuidor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDistribuidor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDistribuidor3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        List<String> errores = new ArrayList();

        if (txtNombre.getText().equals("")) {
            errores.add("Debe ingresar un nombre");
        }
        if (cbxTipo.getSelectedItem().equals("Seleccionar")) {
            errores.add("Debe seleccionar un tipo");
        }
        if (!rbDistribuidor1.isSelected() && !rbDistribuidor2.isSelected() && !rbDistribuidor3.isSelected()) {
            errores.add("Sebe seleccionar un distribuidor");
        }
        if (!chkSucursal1.isSelected() && !chkSucursal2.isSelected()) {
            errores.add("Debe seleccionar al menos una sucursal");
        }
        if ((int) spinCantidad.getValue() < 0) {
            errores.add("Debe ingresar un número mayor a cero");
        }
        if (errores.size() > 0) {
            String error = "";
            for (String e : errores) {
                error += e + "<br>";
            }
            txtError.setText("<html>" + error + "</html>");
            //System.out.println(error);
        } else {
           Pedido p = new Pedido();
           Medicamento m = new Medicamento();
           m.setNombre(txtNombre.getText());
           m.setTipo(cbxTipo.getSelectedItem().toString());
           p.setMedicamento(m);
           p.setDistribuidor("");
             
        rbDistribuidor1.setSelected(false);
        rbDistribuidor2.setSelected(false);
        rbDistribuidor3.setSelected(false);
        chkSucursal1.setSelected(false);
        chkSucursal2.setSelected(false);
        spinCantidad.setValue(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JCheckBox chkSucursal1;
    private javax.swing.JCheckBox chkSucursal2;
    private javax.swing.ButtonGroup grpDistribuidor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbDistribuidor1;
    private javax.swing.JRadioButton rbDistribuidor2;
    private javax.swing.JRadioButton rbDistribuidor3;
    private javax.swing.JSpinner spinCantidad;
    private javax.swing.JLabel txtError;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
